#!/usr/bin/env sh
if ! test "$BUILD_DIR"; then
	echo "BUILD_DIR is not set, defaulting to _build"
	BUILD_DIR="_build"
fi

if test $1; then
	if test $1 = "-c"; then
		cmake --build "$BUILD_DIR" --target clean
	else
		echo "The only supported command line option is -c (clean before build)"
	fi
fi

BUILD_SHARED_LIBS="ON"
USE_GPU="ON"
GPU="ON"
USE_CUDNN="ON"
CUDNN_HALF="ON"

# @todo would be nice to have command line options to enable the compile options
#       easily but that would require some work on the option parsing
cmake . -B"$BUILD_DIR" \
	-DUSE_GPU="$USE_GPU" \
	-DUSE_CUDNN="$USE_CUDNN" \
	-DCUDNN_HALF="$CUDNN_HALF" \
	-DBUILD_SHARED_LIBS="$BUILD_SHARED_LIBS" \
    -DGPU="$GPU"


# @todo would be nice to have a command line option to enable verbose, or parallel processing
#       but that would require some work on the option parsing
cmake --build "$BUILD_DIR" -- -j"$(nproc)"
# cmake --build "$BUILD_DIR" -- -j1
# cmake --build "$BUILD_DIR" -- VERBOSE=1 -j"$(nproc)"
# cmake --build "$BUILD_DIR" -- VERBOSE=1 -j1

echo
echo "To run the tests:"
echo "CTEST_OUTPUT_ON_FAILURE=1 cmake --build \"$BUILD_DIR\" --target test"
