#!/usr/bin/env sh
BUILD_DIR="_build"
CLEAN_OPT=""
if test $1; then
	if test $1 = "-c"; then
		CLEAN_OPT="--clean-first"
	else
		echo "The only supported command line option is -c (clean before build)"
	fi
fi
# @todo would be nice to have a command line option to enable verbose, or parallel processing
#       but that would require some work on the option parsing
COMMAND="cmake --build "$BUILD_DIR" "$CLEAN_OPT" -- -j"$(nproc)""
# COMMAND="cmake --build "$BUILD_DIR" "$CLEAN_OPT" -- VERBOSE=1 -j"$(nproc)""
# COMMAND="cmake --build "$BUILD_DIR" "$CLEAN_OPT" -- VERBOSE=1 -j1"
# COMMAND="cmake --build "$BUILD_DIR" "$CLEAN_OPT" -- -j1"
echo "Calling: $COMMAND"
$COMMAND

if test $_; then
	cmake --build "$BUILD_DIR" --target test
fi
